Repository unikraft/catalog, pull requests merged in 2024-03, with the labels that each got.

#62 fix(examples): Improve README for http-python3.10
  examples/http-python3.10/README.md
Labels: enhancement

#63 fix(examples): Improve README for http-python3.10
  examples/http-python3.10/README.md
Labels: documentation, enhancement

#23 feat(library): Introduce Ruby as library
  .github/workflows/library-ruby3.2.yaml
  README.md
  library/ruby/3.2/.dockerignore
  library/ruby/3.2/.gitignore
  library/ruby/3.2/Dockerfile
  library/ruby/3.2/Kraftfile
  library/ruby/3.2/README.md
  library/ruby/3.2/server.rb
Labels: enhancement

#24 feat(library): Introduce PHP as library
  .github/workflows/library-php8.2.yaml
  README.md
  library/php/8.2/.dockerignore
  library/php/8.2/.gitignore
  library/php/8.2/Dockerfile
  library/php/8.2/Kraftfile
  library/php/8.2/README.md
  library/php/8.2/php.ini
  library/php/8.2/server.php
Labels: enhancement

#28 feat(library): Introduce Perl 5.38 as library
  .github/workflows/library-perl5.38.yaml
  README.md
  library/perl/5.38/.dockerignore
  library/perl/5.38/.gitignore
  library/perl/5.38/Dockerfile
  library/perl/5.38/Kraftfile
  library/perl/5.38/README.md
  library/perl/5.38/server.pl
Labels: enhancement

#68 fix(examples): Improve http-python3.10 README
  examples/http-python3.10/README.md
Labels: documentation, enhancement

#49 feat(library): Introduce Memcached 1.6 as library
  .github/workflows/library-memcached1.6.yaml
  README.md
  library/memcached/1.6/.dockerignore
  library/memcached/1.6/.gitignore
  library/memcached/1.6/Dockerfile
  library/memcached/1.6/Kraftfile
  library/memcached/1.6/README.md
Labels: enhancement

#69 feat(examples): Add Rust examples
  README.md
  examples/http-rust1.75-actix-web4/Cargo.toml
  examples/http-rust1.75-actix-web4/Dockerfile
  examples/http-rust1.75-actix-web4/Kraftfile
  examples/http-rust1.75-actix-web4/README.md
  examples/http-rust1.75-actix-web4/src/main.rs
  examples/http-rust1.75-rocket0.5/Cargo.toml
  examples/http-rust1.75-rocket0.5/Dockerfile
  examples/http-rust1.75-rocket0.5/Kraftfile
  examples/http-rust1.75-rocket0.5/README.md
  examples/http-rust1.75-rocket0.5/Rocket.toml
  examples/http-rust1.75-rocket0.5/src/main.rs
  examples/http-rust1.75-tokio/Cargo.toml
  examples/http-rust1.75-tokio/Dockerfile
  examples/http-rust1.75-tokio/Kraftfile
  examples/http-rust1.75-tokio/README.md
  examples/http-rust1.75-tokio/src/main.rs
  examples/http-rust1.75/Dockerfile
  examples/http-rust1.75/Kraftfile
  examples/http-rust1.75/README.md
  examples/http-rust1.75/server.rs
Labels: documentation, enhancement

#81 feat(library): Introduce NodeJS 19 as library
  library/node/19/.dockerignore
  library/node/19/.gitignore
  library/node/19/Dockerfile
  library/node/19/Kraftfile
  library/node/19/README.md
  library/node/19/server.js
Labels: documentation, enhancement

#83 feat(library): Introduce NodeJS 21 as library
  .github/workflows/library-node21.yaml
  README.md
  library/node/21/.dockerignore
  library/node/21/.gitignore
  library/node/21/Dockerfile
  library/node/21/Kraftfile
  library/node/21/README.md
  library/node/21/server.js
Labels: documentation, enhancement

#71 feat(examples): Add Ruby and Perl examples
  examples/http-perl5.38/.dockerignore
  examples/http-perl5.38/.gitignore
  examples/http-perl5.38/Dockerfile
  examples/http-perl5.38/Kraftfile
  examples/http-perl5.38/README.md
  examples/http-perl5.38/server.pl
  examples/http-ruby3.2/.dockerignore
  examples/http-ruby3.2/.gitignore
  examples/http-ruby3.2/Dockerfile
  examples/http-ruby3.2/Kraftfile
  examples/http-ruby3.2/README.md
  examples/http-ruby3.2/server.rb
Labels: documentation, enhancement

#73 feat(examples): Add PHP example
  examples/http-php8.2/.dockerignore
  examples/http-php8.2/.gitignore
  examples/http-php8.2/Dockerfile
  examples/http-php8.2/Kraftfile
  examples/http-php8.2/README.md
  examples/http-php8.2/php.ini
  examples/http-php8.2/server.php
Labels: documentation, enhancement

#78 feat(examples): Add Redis example
  examples/redis/.dockerignore
  examples/redis/.gitignore
  examples/redis/Dockerfile
  examples/redis/Kraftfile
  examples/redis/README.md
Labels: documentation, enhancement

#55 feat(examples): Introduce HTTP Flask server as example
  examples/http-python3.12-flask3.0/.dockerignore
  examples/http-python3.12-flask3.0/.gitignore
  examples/http-python3.12-flask3.0/Dockerfile
  examples/http-python3.12-flask3.0/Kraftfile
  examples/http-python3.12-flask3.0/README.md
  examples/http-python3.12-flask3.0/requirements.txt
  examples/http-python3.12-flask3.0/server.py
Labels: documentation, enhancement

#90 feat(examples): Introduce HTTP Node21 example
  examples/http-node21/.dockerignore
  examples/http-node21/.gitignore
  examples/http-node21/Dockerfile
  examples/http-node21/Kraftfile
  examples/http-node21/README.md
  examples/http-node21/server.js
Labels: documentation, enhancement

#93 feat(examples): Introduce Caddy example
  examples/caddy/.dockerignore
  examples/caddy/.gitignore
  examples/caddy/Kraftfile
  examples/caddy/README.md
  examples/caddy/rootfs/etc/caddy/Caddyfile
  examples/caddy/rootfs/var/www/index.html
Labels: documentation, enhancement

#94 fix(library): Add user-provided EINITRD support
  library/caddy/2.7/Kraftfile
  library/hugo/0.122/Kraftfile
  library/lua/5.4.4/Kraftfile
  library/memcached/1.6/Kraftfile
  library/nginx/1.25/Kraftfile
  library/node/18/Kraftfile
  library/node/21/Kraftfile
  library/perl/5.38/Kraftfile
  library/php/8.2/Kraftfile
  library/python/3.12/Kraftfile
  library/redis/7.2/Kraftfile
  library/ruby/3.2/Kraftfile
  library/skipper/0.18/Kraftfile
Labels: enhancement

#92 fix(examples): Update some examples to newer README.md format
  examples/http-go1.21/README.md
  examples/http-node18/README.md
  examples/http-python3.10-flask3.0/README.md
Labels: documentation

#95 feat(node18): Use alpine Dockerfile
  library/node/18/Dockerfile
Labels: enhancement

#82 feat(library): Introduce NodeJS 20 as library
  .github/workflows/library-node20.yaml
  README.md
  library/node/20/.dockerignore
  library/node/20/.gitignore
  library/node/20/Dockerfile
  library/node/20/Kraftfile
  library/node/20/README.md
  library/node/20/server.js
Labels: documentation, enhancement

#97 feat(examples): Update helloworld-rs
  native/helloworld-rs/.gitignore
  native/helloworld-rs/Cargo.lock
  native/helloworld-rs/Cargo.toml
  native/helloworld-rs/Kraftfile
  native/helloworld-rs/README.md
  native/helloworld-rs/src/main.rs
Labels: documentation, enhancement

#104 feat(examples): Add Node 21 Prisma example
  examples/node21-prisma-rest-express/.dockerignore
  examples/node21-prisma-rest-express/.gitignore
  examples/node21-prisma-rest-express/Dockerfile
  examples/node21-prisma-rest-express/Kraftfile
  examples/node21-prisma-rest-express/README.md
  examples/node21-prisma-rest-express/README.prisma.md
  examples/node21-prisma-rest-express/package.json
  examples/node21-prisma-rest-express/prisma/migrations/20240208151224_init/migration.sql
  examples/node21-prisma-rest-express/prisma/migrations/migration_lock.toml
  examples/node21-prisma-rest-express/prisma/schema.prisma
  examples/node21-prisma-rest-express/prisma/seed.js
  examples/node21-prisma-rest-express/src/index.js
  examples/node21-prisma-rest-express/webpack.config.js
Labels: enhancement

#105 feat(examples): Add Node 21 ExpressJS example
  examples/node21-expressjs/.dockerignore
  examples/node21-expressjs/.gitignore
  examples/node21-expressjs/Dockerfile
  examples/node21-expressjs/Kraftfile
  examples/node21-expressjs/README.md
  examples/node21-expressjs/app/index.js
  examples/node21-expressjs/package.json
Labels: enhancement

#106 .github/workflows: Add option to start workflows remotely
  .github/workflows/library-base.yaml
  .github/workflows/library-caddy2.7.yaml
  .github/workflows/library-helloworld.yaml
  .github/workflows/library-hugo0.122.yaml
  .github/workflows/library-lua5.4.4.yaml
  .github/workflows/library-lua5.4.yaml
  .github/workflows/library-memcached1.6.yaml
  .github/workflows/library-nginx1.15.yaml
  .github/workflows/library-nginx1.25.yaml
  .github/workflows/library-node18.yaml
  .github/workflows/library-node20.yaml
  .github/workflows/library-node21.yaml
  .github/workflows/library-perl5.38.yaml
  .github/workflows/library-php8.2.yaml
  .github/workflows/library-python3.10.yaml
  .github/workflows/library-python3.12.yaml
  .github/workflows/library-redis7.0.yaml
  .github/workflows/library-redis7.2.yaml
  .github/workflows/library-ruby3.2.yaml
  .github/workflows/library-skipper0.18.yaml
  .github/workflows/library-sqlite3.40.yaml
Labels: enhancement
